<?php

/**
 * Implements hook_install().
 */
function glossary_tooltip_install() {

  // Checking if the dictionary already exists.
  if (!\Drupal::entityTypeManager()->getStorage('taxonomy_vocabulary')->load('glossary')) {

    // Creating a 'Glossary' dictionary.
    $vocabulary = \Drupal\taxonomy\Entity\Vocabulary::create([
      'vid' => 'glossary',
      'name' => 'Glossary',
    ]);
    $vocabulary->save();
  }
}

